### ISSUE TITLE
[Bug] 在钓鱼中，“拌线钩”名称有错别字，应为“绊线钩”

### ISSUE THREAD

**Issue by EatHatsuneShallots** [FloatTech/zbpdata#58]
如题，最好兼容一下以前的物品
~~居然一直都没有人发现~~

**Comment by fumiama** [comment]
@fangliuyu

**Comment by fangliuyu** [comment]
fix at #60[https://github.com/FloatTech/zbpdata/pull/60](url)

**Comment by EatHatsuneShallots** [comment]
@fangliuyu 那之前的“拌线钩”物品该怎么办呢，总不能一直留在背包里吧

**Comment by fangliuyu** [comment]
> @fangliuyu 那之前的“拌线钩”物品该怎么办呢，总不能一直留在背包里吧

卖掉就好了，收入为0

**Comment by EatHatsuneShallots** [comment]
> 卖掉就好了，收入为0

是要用“出售全部垃圾”吗，“出售拌线钩999”不识别
