### ISSUE TITLE
求Fortune签底资源

### ISSUE THREAD

**Issue by KafCoppelia** [FloatTech/zbpdata#8]
你好，我是Nonebot2的开发者。
[nonebot_plugin_fortune](https://github.com/KafCoppelia/nonebot_plugin_fortune)迁移到了nb2上并使用了您的主题资源，我希望得到[Fortune](https://github.com/FloatTech/zbpdata/tree/main/Fortune)系列的抽签签底图片资源（没有角色在上面），以扩充更多的抽签样式。签底与角色立绘是通过什么方法加在一起的呢？

如果可以，不胜感激。🙏

**Comment by fumiama** [comment]
请加zbp交流群，群文件里有。群号在 https://github.com/FloatTech/ZeroBot-Plugin README。

**Comment by KafCoppelia** [comment]
感谢
